### ISSUE TITLE
update site link not working

### ISSUE THREAD

**Issue by seralf** [AKSW/Xturtle#71]
Hi

the url for the update site (for installation) seems not to work: http://xturtle.aksw.org/site.xml

**Comment by nittka** [comment]
Thanks for letting us know. Could you use https://raw.githubusercontent.com/AKSW/Xturtle/gh-pages/site.xml for the moment (this is where the above URL should redirect to)?

A snapshot version with a couple of small fixes is also available at http://xturtle.nittka.de/snapshot/site.xml.

@seebi: Could you please check what happened to the redirect?

**Comment by seralf** [comment]
thank you for the fast reply! :-)

I'll try the snapshot then, thanks again

**Comment by seebi** [comment]
@white-gecko Can you please check this issue, I do not have any access to AKSW infrastructure anymore ...

**Comment by nittka** [comment]
@seebi: Is it possible that the gh-pages CNAME file does not work as intended, anymore?

**Comment by white-gecko** [comment]
http://aksw.org/Projects/Xturtle works, but http://aksw.org/Projects/Xturtlesite.xml obviously doesn't.

There is something wrong with the redirect from `http://xturtle.aksw.org` maybe it should except certain URLs/paths or only redirect for specific URLs/paths.

```
$ curl -L -I http://xturtle.aksw.org/site.xml
HTTP/1.1 301 Moved Permanently
Date: Wed, 18 May 2016 21:03:04 GMT
Server: Apache/2.4.10 (Debian)
Location: http://aksw.org/Projects/Xturtlesite.xml
Content-Type: text/html; charset=iso-8859-1

HTTP/1.1 404 Not Found
Date: Wed, 18 May 2016 21:03:04 GMT
Server: Apache/2.4.7 (Ubuntu)
X-Powered-By: PHP/5.5.9-1ubuntu4.16
Set-Cookie: PHPSESSID=p538nohjd9pg29g5g4f9oludi3; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Access-Control-Allow-Origin: *
Content-Type: text/html

$ curl -L -I http://xturtle.aksw.org/        
HTTP/1.1 301 Moved Permanently
Date: Wed, 18 May 2016 21:03:18 GMT
Server: Apache/2.4.10 (Debian)
Location: http://aksw.org/Projects/Xturtle
Content-Type: text/html; charset=iso-8859-1

HTTP/1.1 302 Found
Date: Wed, 18 May 2016 21:03:18 GMT
Server: Apache/2.4.7 (Ubuntu)
X-Powered-By: PHP/5.5.9-1ubuntu4.16
Set-Cookie: PHPSESSID=c0e2pi727ie0mgthdm50nbqpj6; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Location: http://aksw.org/Projects/Xturtle.html
Content-Type: text/html

HTTP/1.1 200 OK
Date: Wed, 18 May 2016 21:03:18 GMT
Server: Apache/2.4.7 (Ubuntu)
X-Powered-By: PHP/5.5.9-1ubuntu4.16
Set-Cookie: PHPSESSID=im4gjqnp12gko1ccl61han7os5; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Access-Control-Allow-Origin: *
Content-Type: text/html; encoding=utf-8
```

**Comment by white-gecko** [comment]
Ok, it should be fixed for http://xturtle.aksw.org/site.xml . Are there other URLs with need special treatment as well?

**Comment by nittka** [comment]
Although redirection works in the browser, the URL is not recognized as valid update site by Eclipse (trying to install from that location does not show any content).

Option 1 is trying to make the redirect work somehow else.

Option 2 is placing a composite update site on the AKSW server. See https://github.com/AKSW/Xturtle/tree/gh-pages/snapshot for an example. There could be a directory http://xturtle.aksw.org/updatesite with the three files, the XML files directly pointing to the gh-pages site.xml. I'll have to check that updates to the site are actually recognized by Eclipse (as the composite site does not change, caching may prevent visiting site.xml again).

**Comment by white-gecko** [comment]
Ok, I've changed the redirect to use rawgit, which serves it with a `text/xml` content type. It also caches the site.xml (CDN) if it is changing frequently we should use the other rawgit URL.

What is about the `features/de.itemis.tooling.xturtle.feature_1.0.1.jar` files, are they expected by eclipse to be served from `xturtle.aksw.org` as well, or will it asume the base URL of the redirect target?

**Comment by nittka** [comment]
The update site mechanism is still not working - probably because of the relative paths within the site.xml. I don't known whether redirecting those two directories suffices.

The site.xml hosted on gh-pages will change - not frequently, but still. I would not be nice, if we had file an issue every time a new release is available to make sure the cache will not yield the old version for 2 more weeks.

I'd almost prefer Option 2, where Eclipse is redirected physically to gh-pages to look for the actual site.xml and no changes are required on the AKSW-side in case of new releases.

I will try out that way next week and come back with a suggestion.

**Comment by seebi** [comment]
@white-gecko can you please forward
http://xturtle.aksw.org/features/*
to
https://cdn.rawgit.com/AKSW/Xturtle/gh-pages/features/*

**Comment by white-gecko** [comment]
done

**Comment by nittka** [comment]
Ok, I have played around a bit and this is what I suggest.

The current redirects still do not work and as explained in https://github.com/rgrove/rawgit/wiki/Frequently-Asked-Questions we cannot use redirects to cdn.rawgit due to the caching - at least not for site.xml or other update site files (jars should be fine).

My suggestion:
- remove all forwardings from xturtle.aksw.org to github
- place the update site files I prepared such that they are located at http://xturtle.aksw.org (@seebi or http://xturtle.aksw.org/updatesite ?)
- update the installation instructions on http://aksw.org/Projects/Xturtle.html pointing to that new location

The update site files redirect (via rawgit) to the gh-pages update site in a way that everything should still work if we change to an update site layout different from the current site.xml.

@seebi and @white-gecko: I'll send you the update site files by email.

**Comment by nittka** [comment]
The following update site URLs should now work due to redirects configured for xturtle.aksw.org:
- http://xturtle.aksw.org/site.xml
- http://xturtle.aksw.org/updatesite
- http://xturtle.aksw.org/updatesite/

As a positive side effect http://xturtle.aksw.org/updatesite/snapshot (also) works as snapshot update site location.

**Comment by smnmyr** [comment]
@nittka None of these sites work at the moment.

As a temporary workaround, https://raw.githubusercontent.com/AKSW/Xturtle/gh-pages/site.xml remains reachable though.

**Comment by nittka** [comment]
@white-gecko: Did the redirects we defined for the above pages change, again?

I can confirm that the first URL does not work in Eclipse (when the redirect was first defined it worked).

@smnmyr: Could you please try removing all xturtle related update sites from Eclipse's "Available Software Sites" and then add one of the last two again? These work for me...

**Comment by white-gecko** [comment]
No, it is still:

```
<VirtualHost *>
    Use TemplateServerBlock "my-email-is-here" "xturtle.aksw.org" "*.xturtle.aksw.org"
    Redirect /site.xml https://raw.githubusercontent.com/AKSW/Xturtle/gh-pages/
    Redirect /features/ https://raw.githubusercontent.com/AKSW/Xturtle/gh-pages/features/
    Redirect /features https://raw.githubusercontent.com/AKSW/Xturtle/gh-pages/features
    Redirect /updatesite/ https://raw.githubusercontent.com/AKSW/Xturtle/gh-pages/
    Redirect /updatesite https://raw.githubusercontent.com/AKSW/Xturtle/gh-pages
    Redirect / http://aksw.org/Projects/Xturtle
</VirtualHost>
```

**Comment by nittka** [comment]
Are you sure it was https from the beginnig? I thought, we used http...

**Comment by white-gecko** [comment]
Yes, I think it was https, should I change it to http? Does eclipse cause trouble with https?

**Comment by nittka** [comment]
Yes, please change the target URLs to http for now.

**Comment by todolson** [comment]
Just so you know, http://xturtle.aksw.org/site.xml once again is returning `400: Invalid request`.

I have tried using https://raw.githubusercontent.com/AKSW/Xturtle/gh-pages/site.xml to install Xturtle, that was successful.

**Comment by seebi** [comment]
@white-gecko since we have important users here, we should fix this ...

**Comment by white-gecko** [comment]
I hope it is fixed now. Could someone please check if it actually works with eclipse?

**Comment by nittka** [comment]
For me, the update site links work again.
